<?php

namespace AppBundle\Repository;

/**
 * PostCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findShown()
    {
        return $this->createQueryBuilder('c')
            ->where('c.isVisible = true')
            ->addOrderBy('c.label', 'ASC')
            ->getQuery()->getResult();
    }
}
