<?php

namespace AppBundle\Repository;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPost($post, $page = 1, $maxResult = 10)
    {
        $first = ($page - 1) * ($maxResult - 1);

        return $this->createQueryBuilder('c')
            ->where('c.post = :post')
                ->setParameter('post', $post)
            ->orderBy('c.insertedAt', 'ASC')
            ->addOrderBy('c.id', 'ASC')
            ->setFirstResult($first)
            ->setMaxResults($maxResult)
            ->getQuery()->getResult();
    }
}
