admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"